app:
  replicas: 2

image: 
  repository: heena2325/hello-world-py-2
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m


service:
  type: LoadBalancer
  port: 80
