apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ include "demo-python-app.name" . | nindent 4}}
  template:
    metadata:
      labels:
        app: {{ include "demo-python-app.name" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
        {{ toYaml .Values.resources | nindent 12 }}
        
