apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "demo-python-app.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
    
